# Generated by Django 5.2.16 on 2026-07-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField()),
                ('owner', models.CharField(max_length=255)),
                ('repo', models.CharField(max_length=255)),
                ('commit_hash', models.CharField(max_length=64)),
                ('feature_title', models.CharField(max_length=500)),
                ('feature_category', models.CharField(max_length=100)),
                ('verdict', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
